server:
  port: 8082



#person:
#    age: 22
#    boss: false
#    birth: 2017/12/12
#    maps: {k1: v1,k2: 12}
#    list:
#      - lisi
#      - zhangsan
#    dog:
#      name: 小狗
#      age: 2
#    last-name: zhangsan